/* eslint-disable no-undef */
export const KANDIDATSOK_API =
    window.KANDIDAT_KANDIDATSOK_API || process.env.REACT_APP_KANDIDAT_KANDIDATSOK_API;
export const SEARCH_API = `${KANDIDATSOK_API}/veileder/kandidatsok`;
export const KANDIDATLISTE_API = `${KANDIDATSOK_API}/veileder`;
export const KODEVERK_API = `${KANDIDATSOK_API}/kodeverk`;
export const LOGIN_URL = window.KANDIDAT_LOGIN_URL || process.env.REACT_APP_KANDIDAT_LOGIN_URL;
export const PAM_SEARCH_API_GATEWAY_URL =
    window.KANDIDAT_PAM_SEARCH_API_GATEWAY_URL ||
    process.env.REACT_APP_KANDIDAT_PAM_SEARCH_API_GATEWAY_URL;
export const LAST_NED_CV_URL =
    window.KANDIDAT_LAST_NED_CV_URL || process.env.REACT_APP_KANDIDAT_LAST_NED_CV_URL;
export const ARBEIDSRETTET_OPPFOLGING_URL =
    window.KANDIDAT_ARBEIDSRETTET_OPPFOLGING_URL ||
    process.env.REACT_APP_KANDIDAT_ARBEIDSRETTET_OPPFOLGING_URL;
export const MIDLERTIDIG_UTILGJENGELIG_PROXY =
    window.KANDIDAT_MIDLERTIDIG_UTILGJENGELIG_PROXY ||
    process.env.REACT_APP_KANDIDAT_MIDLERTIDIG_UTILGJENGELIG_PROXY;
export const SMS_PROXY = window.KANDIDAT_SMS_PROXY || process.env.REACT_APP_KANDIDAT_SMS_PROXY;
