/* eslint-disable no-undef */
export const LOGIN_URL = window.KANDIDAT_LOGIN_URL || process.env.REACT_APP_LOGIN_URL;
export const PAM_SEARCH_API_GATEWAY_URL =
    window.KANDIDAT_ENHETSREGISTER_URL || process.env.REACT_APP_ENHETSREGISTER_URL;
export const LAST_NED_CV_URL =
    window.KANDIDAT_LAST_NED_CV_URL || process.env.REACT_APP_LAST_NED_CV_URL;
export const ARBEIDSRETTET_OPPFOLGING_URL =
    window.KANDIDAT_ARBEIDSRETTET_OPPFOLGING_URL ||
    process.env.REACT_APP_ARBEIDSRETTET_OPPFOLGING_URL;
export const MIDLERTIDIG_UTILGJENGELIG_PROXY =
    window.KANDIDAT_MIDLERTIDIG_UTILGJENGELIG_PROXY ||
    process.env.REACT_APP_MIDLERTIDIG_UTILGJENGELIG_PROXY;
export const SMS_PROXY = window.KANDIDAT_SMS_PROXY || process.env.REACT_APP_SMS_PROXY;
