apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-kandidat
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    liveness:
        path: /rekrutteringsbistand/internal/isAlive
        initialDelay: 5
    readiness:
        path: /rekrutteringsbistand/internal/isReady
        initialDelay: 5
    ingresses:
        - https://arbeidsgiver.labs.nais.io/rekrutteringsbistand
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LAST_NED_CV_URL
          value: '#'
        - name: ARBEIDSRETTET_OPPFOLGING_URL
          value: '#'
