apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-kandidat
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /rekrutteringsbistand-kandidat/internal/isAlive
        initialDelay: 15
        timeout: 1
        failureThreshold: 2
    readiness:
        path: /rekrutteringsbistand-kandidat/internal/isReady
        initialDelay: 15
        timeout: 1
    replicas:
        min: 1
        max: 2
    cpuThresholdPercentage: 50
    resources:
        limits:
            cpu: 500m
            memory: 512Mi
        requests:
            cpu: 200m
            memory: 256Mi
    ingresses:
        - https://arbeidsgiver.labs.nais.io/rekrutteringsbistand-kandidat
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LAST_NED_CV_URL
          value: '#'
        - name: ARBEIDSRETTET_OPPFOLGING_URL
          value: '#'
