apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-kandidat-labs
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    liveness:
        path: /rekrutteringsbistand-kandidat/internal/isAlive
        initialDelay: 5
    readiness:
        path: /rekrutteringsbistand-kandidat/internal/isReady
        initialDelay: 5
    ingresses:
        - https://rekrutteringsbistand.labs.nais.io
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LAST_NED_CV_URL
          value: '#'
        - name: ARBEIDSRETTET_OPPFOLGING_URL
          value: '#'
