/* eslint-disable no-undef */
export const LAST_NED_CV_URL =
    window.KANDIDAT_LAST_NED_CV_URL || process.env.REACT_APP_LAST_NED_CV_URL;
export const ARBEIDSRETTET_OPPFOLGING_URL =
    window.KANDIDAT_ARBEIDSRETTET_OPPFOLGING_URL ||
    process.env.REACT_APP_ARBEIDSRETTET_OPPFOLGING_URL;
